version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "tableau-data-workflow"
s3_bucket = "my-deployment-artifacts"
s3_prefix = "tableau-data-workflow"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
    "ClusterArn=arn:aws:ecs:us-east-1:123456789012:cluster/data-processing",
    "SubnetIds=subnet-abc123,subnet-def456",
    "SecurityGroupIds=sg-abc123",
    "TaskRoleArn=arn:aws:iam::123456789012:role/ecsTaskExecutionRole"
]
